print("Hello World!!!")
print("This is Helge Siegel calling" )
print("Day of my forceps delivery: strictly private catatstrophe anniversary")
print(" Not toi be known to everyone!")
print(" ")
print("presently undergoing a study as a Bioinformatician and Biostatistician")
print(" laughing 'bout that?????")
print(" STOP!!!")
print("Angewandte Bioinformatik und Biostatistik")
print("Alway keep that in mind ")
print("Siempre lo recuerda!")
